### ISSUE TITLE
Compile failure - missing header files

### ISSUE THREAD

**Issue by gravitystorm** [zerebubuth/cgimap-ruby#3]
When compiling with `bundle exec rake compile` I get

`conftest.c:3:42: fatal error: cgimap/backend/apidb/apidb.hpp: No such file or directory`

That hpp file isn't installed by openstreetmap-cgimap `make install`. The full list of installed headers corresponds to https://github.com/zerebubuth/openstreetmap-cgimap/blob/library_split/Makefile.am#L9, namely:

```
vagrant@default-ubuntu-1410:/usr/local/include/cgimap$ ls -l
total 68
-rw-r--r-- 1 root root 1573 Feb 24 15:09 backend.hpp
-rw-r--r-- 1 root root  929 Feb 24 15:09 bbox.hpp
-rw-r--r-- 1 root root 2997 Feb 24 15:09 config.hpp
-rw-r--r-- 1 root root 3564 Feb 24 15:09 data_selection.hpp
-rw-r--r-- 1 root root 1314 Feb 24 15:09 handler.hpp
-rw-r--r-- 1 root root 4419 Feb 24 15:09 http.hpp
-rw-r--r-- 1 root root  334 Feb 24 15:09 logger.hpp
-rw-r--r-- 1 root root  459 Feb 24 15:09 mime_types.hpp
-rw-r--r-- 1 root root  339 Feb 24 15:09 output_buffer.hpp
-rw-r--r-- 1 root root 3251 Feb 24 15:09 output_formatter.hpp
-rw-r--r-- 1 root root  508 Feb 24 15:09 process_request.hpp
-rw-r--r-- 1 root root  474 Feb 24 15:09 rate_limiter.hpp
-rw-r--r-- 1 root root 1278 Feb 24 15:09 request_helpers.hpp
-rw-r--r-- 1 root root 3821 Feb 24 15:09 request.hpp
-rw-r--r-- 1 root root  975 Feb 24 15:09 routes.hpp
-rw-r--r-- 1 root root  109 Feb 24 15:09 types.hpp
```

Full logs
* `bundle exec rake compile` https://gist.github.com/gravitystorm/c4277338a2e6af2a0f43
* `mkmf.log` https://gist.github.com/gravitystorm/1685a3b6acc8ddf4c658

**Comment by zerebubuth** [comment]
Fixed upstream in [this commit](https://github.com/zerebubuth/openstreetmap-cgimap/commit/73279c1fdbd0b3beb989553641b5c0a95e55a89b). Hopefully it also works for you now.
